Repository web-auth/webauthn-framework, pull requests merged in 2023-09, with the labels that each got.

#467 Fixed configuration for authenticator selection criteria
  src/symfony/src/DependencyInjection/Configuration.php
  tests/symfony/config/config.yml
Labels: bug

#473 NoneAttestationStatementSupport enabled by default
  src/webauthn/src/AttestationStatement/AttestationStatementSupportManager.php
Labels: DX

#487 The list of PKC Params is empty by default and not required anymore
  src/webauthn/src/PublicKeyCredentialCreationOptions.php
  tests/library/Functional/AndroidSafetyNetAttestationStatementTest.php
  tests/library/Functional/AppleAttestationStatementTest.php
  tests/library/Functional/AttestationStatementWithTokenBindingTest.php
  tests/library/Functional/Fido2AttestationStatementTest.php
  tests/library/Functional/NoneAttestationStatementTest.php
  tests/library/Functional/PackedAttestationStatementTest.php
  tests/library/Unit/AttestationStatement/TPMAttestationStatementSupportTest.php
  tests/symfony/functional/Attestation/AttestationTest.php
  tests/symfony/functional/Attestation/PackedAttestationStatementTest.php
Labels: enhancement

#489 @private statement removed
  src/webauthn/src/PublicKeyCredentialCreationOptions.php
Labels: bug
