Repository web-auth/webauthn-framework, pull requests merged in 2024-04, with the labels that each got.

#584 Add missing tag to inject configured event dispatcher
  src/symfony/src/DependencyInjection/Factory/Security/WebauthnServicesFactory.php
  src/symfony/src/DependencyInjection/WebauthnExtension.php
Labels: bug

#587 Refactor authenticator response identification logic
  src/webauthn/src/Denormalizer/AuthenticatorResponseDenormalizer.php
  src/webauthn/src/PublicKeyCredentialLoader.php
Labels: bug, compliance

#585 Deprecate Android SafetyNet support
  phpstan-baseline.neon
  src/symfony/src/DependencyInjection/Compiler/EnforcedSafetyNetApiKeyVerificationCompilerPass.php
  src/symfony/src/DependencyInjection/Configuration.php
  src/symfony/src/DependencyInjection/WebauthnExtension.php
  src/symfony/src/Resources/config/android_safetynet.php
  src/webauthn/composer.json
  src/webauthn/src/AttestationStatement/AndroidSafetyNetAttestationStatementSupport.php
Labels: compliance

#592 Add new fields to PublicKeyCredentialSource mapping
  src/symfony/src/Resources/config/doctrine-mapping/PublicKeyCredentialSource.orm.xml
Labels: bug
