Repository web-auth/webauthn-framework, pull requests merged in 2025-03, with the labels that each got.

#701 Refactor and improve Webauthn handling, tests, and configs.
  composer.json
  phpstan-baseline.neon
  phpunit.xml.dist
  src/stimulus/assets/dist/controller.d.ts
  src/stimulus/assets/dist/controller.js
  src/stimulus/assets/src/controller.ts
  src/symfony/src/Controller/AssertionControllerFactory.php
  src/symfony/src/Controller/AttestationControllerFactory.php
  src/symfony/src/DependencyInjection/Configuration.php
  src/symfony/src/DependencyInjection/Factory/Security/WebauthnFactory.php
  src/symfony/src/DependencyInjection/WebauthnExtension.php
  src/symfony/src/Resources/config/cose.php
  src/symfony/src/Resources/config/dev_services.php
  src/symfony/src/Resources/config/metadata_statement_supports.php
  src/symfony/src/Resources/config/security.php
  src/symfony/src/Resources/config/services.php
  src/symfony/src/Security/WebauthnFirewallConfig.php
  tests/library/Functional/AttestationTest.php
  tests/library/Functional/ConformanceTest.php
  tests/library/Unit/AttestationStatement/TPMAttestationStatementSupportTest.php
  tests/library/Unit/MetadataServiceTest.php
  tests/symfony/config/config.yml
  tests/symfony/functional/Firewall/SecuredAreaTest.php
Labels: DX, UX

#702 Deprecate DoctrineCredentialSourceRepository in Symfony.
  src/symfony/src/Repository/DoctrineCredentialSourceRepository.php
Labels: DX

#698 Restore compatibility with Doctrine DBAL version 3
  src/symfony/src/Doctrine/Type/AttestedCredentialDataType.php
  src/symfony/src/Doctrine/Type/PublicKeyCredentialDescriptorType.php
  src/symfony/src/Doctrine/Type/TrustPathDataType.php
Labels: bug

#693 Add Webauthn Badge support
  composer.json
  phpstan-baseline.neon
  rector.php
  src/stimulus/.github/close-pull-request.yml
  src/symfony/.github/close-pull-request.yml
  src/symfony/src/Repository/DoctrineCredentialSourceRepository.php
  src/symfony/src/Resources/config/doctrine-mapping/PublicKeyCredentialSource.orm.xml
  src/symfony/src/Resources/config/security.php
  src/symfony/src/Security/Authentication/WebauthnAuthenticator.php
  src/symfony/src/Security/Authentication/WebauthnBadge.php
  src/symfony/src/Security/Authentication/WebauthnBadgeListener.php
  src/symfony/src/Security/Authentication/WebauthnPassport.php
  src/webauthn/.github/close-pull-request.yml
  tests/symfony/config/config.yml
  tests/symfony/config/routing.php
  tests/symfony/functional/AdminController.php
  tests/symfony/functional/AppKernel.php
  tests/symfony/functional/Assertion/AssertionTest.php
  tests/symfony/functional/Attestation/AdditionalAuthenticatorTest.php
  tests/symfony/functional/Firewall/AllowedOriginsTest.php
  tests/symfony/functional/Firewall/LegacySecuredAreaTest.php
  tests/symfony/functional/Firewall/NonSecuredAreaTest.php
  tests/symfony/functional/Firewall/RegistrationAreaTest.php
  tests/symfony/functional/Firewall/SecuredAreaTest.php
  tests/symfony/functional/HomeController.php
  tests/symfony/functional/PublicKeyCredentialSourceRepository.php
  tests/symfony/functional/PublicKeyCredentialUserEntityRepository.php
  tests/symfony/functional/SecurityController.php
  tests/symfony/functional/WebauthnAuthenticator.php
  tests/symfony/functional/WebauthnTestCase.php
  tests/symfony/templates/base.html.twig
  tests/symfony/templates/login.html.twig
Labels: enhancement

#704 Add WebAuthn extensions and integrate PRF handling logic
  phpstan-baseline.neon
  src/stimulus/assets/dist/controller.d.ts
  src/stimulus/assets/dist/controller.js
  src/stimulus/assets/src/controller.ts
  src/webauthn/src/AuthenticationExtensions/AppIdExcludeInputExtension.php
  src/webauthn/src/AuthenticationExtensions/AppIdInputExtension.php
  src/webauthn/src/AuthenticationExtensions/CredentialPropertiesInputExtension.php
  src/webauthn/src/AuthenticationExtensions/LargeBlobInputExtension.php
  src/webauthn/src/AuthenticationExtensions/PseudoRandomFunctionInputExtension.php
  src/webauthn/src/AuthenticationExtensions/PseudoRandomFunctionInputExtensionBuilder.php
  src/webauthn/src/AuthenticationExtensions/UvmInputExtension.php
  src/webauthn/src/Denormalizer/AuthenticationExtensionNormalizer.php
Labels: enhancement

#708 Add user provider configuration for Webauthn authentication
  src/symfony/src/Resources/config/security.php
  tests/symfony/config/config.yml
Labels: bug
